[package]
name = "nanika-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nanika-config = { path = "../nanika-config" }
nanika-core = { path = "../nanika-core" }
nanika-extension-package = { path = "../nanika-extension-package" }
nanika-platform = { path = "../nanika-platform" }
nanika-storage = { path = "../nanika-storage" }
zip.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
