[package]
name = "nanika-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
async-process.workspace = true
clipboard-rs.workspace = true
directories.workspace = true
nanika-protocol = { path = "../extension-protocol" }
png.workspace = true
sha2.workspace = true
sys-locale.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_Com", "Win32_System_DataExchange", "Win32_UI_Controls", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
windows-registry.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_Diagnostics_ToolHelp", "Win32_System_JobObjects", "Win32_System_LibraryLoader", "Win32_System_Registry", "Win32_System_SystemInformation", "Win32_System_Threading", "Win32_UI_HiDpi", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
rustix.workspace = true
libc.workspace = true
objc2-service-management = { workspace = true, features = ["std", "objc2", "objc2-foundation", "SMAppService"] }
objc2 = { workspace = true, features = ["std"] }
objc2-app-kit = { workspace = true, features = ["std", "NSEvent", "NSScreen", "NSGraphics", "NSGraphicsContext", "NSImage", "NSImageRep", "NSPasteboard", "NSWorkspace", "objc2-core-foundation", "objc2-core-graphics"] }
objc2-core-foundation = { workspace = true, features = ["std", "CFDictionary", "CFNumber", "CFString", "CFURL"] }
objc2-foundation = { workspace = true, features = ["std", "NSObject", "NSString"] }
objc2-core-graphics = { workspace = true, features = ["std", "CGBitmapContext", "CGColorSpace", "CGContext", "CGImage"] }
objc2-image-io = { workspace = true, features = ["std", "CGImageSource", "objc2-core-graphics"] }
objc2-quick-look-thumbnailing = { workspace = true, features = ["std", "QLThumbnailGenerationRequest", "QLThumbnailGenerator", "QLThumbnailRepresentation", "block2", "objc2-core-foundation", "objc2-core-graphics"] }

[[test]]
name = "ProcessLauncher"
path = "tests/shared/ProcessLauncher.rs"

[[test]]
name = "SingleInstance"
path = "tests/adapters/SingleInstance.rs"

[[test]]
name = "filesystem"
path = "tests/shared/filesystem.rs"
