[package]
name = "nanika-config"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
jsonc-parser.workspace = true
nanika-core = { path = "../domain" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
