[package]
name = "nanika-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
eframe.workspace = true
global-hotkey.workspace = true
wgpu.workspace = true
nanika-core = { path = "../nanika-core" }
nanika-config = { path = "../nanika-config" }
nanika-platform = { path = "../nanika-platform" }
nanika-protocol = { path = "../nanika-protocol" }
nanika-storage = { path = "../nanika-storage" }

[lints]
workspace = true
