[package]
name = "nanika-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[dependencies]
rusqlite.workspace = true
nanika-foundation = { path = "../foundation" }
nanika-platform = { path = "../platform" }
nanika-search = { path = "../search" }
tracing.workspace = true

[lints]
workspace = true
