[package]
name = "nanika-extension-acp-dummy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
agent-client-protocol.workspace = true
async-io.workspace = true

[dev-dependencies]
agent-client-protocol.workspace = true
async-io.workspace = true
futures-lite.workspace = true
nanika-config = { path = "../../crates/nanika-config" }
nanika-extension-package = { path = "../../crates/nanika-extension-package" }
nanika-host = { path = "../../crates/nanika-host" }
nanika-storage = { path = "../../crates/nanika-storage" }
serde_json.workspace = true
zip.workspace = true

[lints]
workspace = true
