[package]
name = "nanika-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[dependencies]
nanika-config = { path = "../../engine/configuration" }
nanika-foundation = { path = "../../engine/foundation" }
nanika-extension-package = { path = "../../engine/extension-management" }
nanika-platform = { path = "../../engine/platform" }
nanika-storage = { path = "../../engine/storage" }
zip.workspace = true

[lints]
workspace = true
