[package]
name = "nanika-extension-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[dependencies]
nanika-platform = { path = "../../../../engine/platform" }
nanika-protocol = { path = "../../../../engine/extension-protocol" }
nanika-text-search = { path = "../../../../engine/text-search" }
rusqlite.workspace = true
png.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
walkdir.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Environment",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation = { workspace = true, features = ["std", "NSArray", "NSBundle", "NSDictionary", "NSEnumerator", "NSFileManager", "NSLocale", "NSProcessInfo", "NSString", "objc2-core-foundation"] }
plist.workspace = true

[lints]
workspace = true

[dev-dependencies]
criterion.workspace = true
nanika-search = { path = "../../../../engine/search" }

[[test]]
name = "main"
path = "tests/main.rs"

[[bench]]
name = "indexing"
harness = false

[[bench]]
name = "search"
harness = false
