[package]
name = "nanika-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
ts-rs = { workspace = true, optional = true }
nanika-protocol = { path = "../extension-protocol" }
nanika-text-search = { path = "../text-search" }
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true

[[bench]]
name = "ranking"
harness = false

[[bench]]
name = "memory"
harness = false

[features]
typescript = ["dep:ts-rs"]
